CREATE TABLE Usuario (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	nome VARCHAR(20) NOT NULL,
	senha VARCHAR(128) NOT NULL,
	email VARCHAR(32) NOT NULL,
	telefone VARCHAR(16) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE KEY UNI_USUARIO_NOME (nome)
);

CREATE TABLE Bico (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	titulo VARCHAR(20) NOT NULL,
	pagamento VARCHAR(128),
	descricao VARCHAR(512),
	PRIMARY KEY (id)
	# UNIQUE KEY UNI_AUT_NOME (AUT_NOME)
);

CREATE TABLE BicoUsuario (
	USR_ID BIGINT UNSIGNED NOT NULL,
	BICO_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (USR_ID, BICO_ID),
	FOREIGN KEY AUT_USUARIO_FK (USR_ID) REFERENCES Usuario (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY AUT_AUTORIZACAO_FK (BICO_ID) REFERENCES Bico (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

# Bcrypt (12 rounds) == admin
# $2a$12$MTWP4jOXyHI6ECZuBypGFOvDkq0LrHWA2QP6d1e9d8YABvZl8MXle

INSERT INTO Usuario VALUES
(
	1,
	'admin',
	'$2a$12$MTWP4jOXyHI6ECZuBypGFOvDkq0LrHWA2QP6d1e9d8YABvZl8MXle',
	'admin@admin.com',
	'4002-8922'
);

# Bcrypt (12 rounds) == guest
# $2a$12$oFQHrLOBxZMdOBTC/n0UZ.rG1zM0U5QdnmpaPFWjSStinhchWeD82

INSERT INTO Usuario VALUES
(
	2,
	'guest',
	'$2a$12$oFQHrLOBxZMdOBTC/n0UZ.rG1zM0U5QdnmpaPFWjSStinhchWeD82',
	'guest@guest.com',
	'1234-5678'
);
